name: 'translate issues'
on: 
  issue_comment: 
    types: [created]
  issues: 
    types: [opened]

jobs:
  translate-isssues:
    name: translate issues
    runs-on: self-hosted
    steps:
      - name: Issues Translator
        uses: tomsun28/issues-translate-action@v2.5
